#!/usr/bin/env sh

# Global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               on

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_opacity               off

yabai -m config mouse_modifier               fn
yabai -m config mouse_drop_action            stack
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

# highlight color for insert placeholder:
yabai -m config insert_feedback_color        0xfff2559e

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   20

# Application rules:
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='Settings$' manage=off

echo "yabai configuration loaded.."
