#!/usr/bin/env bash

yabai_config_args=(
    # Global settings
    window_placement             second_child

    split_ratio                  0.50
    auto_balance                 off

    window_shadow                on
    window_opacity               off

    mouse_modifier               fn
    mouse_drop_action            stack
    mouse_follows_focus          off
    focus_follows_mouse          off

    # highlight color for insert placeholder
    insert_feedback_color        0xfff2559e

    # General space settings
    layout                       bsp
    top_padding                  12
    bottom_padding               12
    left_padding                 12
    right_padding                12
    window_gap                   12
)
yabai -m config "${yabai_config_args[@]}"

# Application rules
yabai -m rule --add app="^System (Preferences|Settings)$" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="CleanShot X" manage=off
yabai -m rule --add app="Slack" manage=off grid=12:9:1:1:7:10
yabai -m rule --add app="iTerm" manage=off grid=12:9:1:1:7:10
yabai -m rule --add app="zoom.us" manage=off grid=12:9:1:1:7:10
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add title='Extension Development Host' manage=off grid=8:8:1:1:6:5

# Apply rules to existing windows
yabai -m rule --apply

# apply borders with github.com/FelixKatz/JankyBorders
borders active_color=0xffff8500 inactive_color=0xff494d64 width=10 &

echo "yabai configuration loaded.."
